# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_auto_20170430_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_recipes', to='main.Profile'),
        ),
    ]
