# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170217_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yummlyrecipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
