# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170217_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yummlyrecipe',
            old_name='calories',
            new_name='time_in_seconds',
        ),
    ]
