# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_recipes',
            field=models.ManyToManyField(to='main.YummlyRecipe'),
        ),
    ]
