# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170405_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='url',
            new_name='yummly_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='bitter',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dateModified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meaty',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='piquant',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='salty',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sour',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='sweet',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
