# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170407_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='raw_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dateCreated',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dateModified',
            field=models.DateTimeField(editable=False),
        ),
    ]
