# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_recipe_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='image_url',
            new_name='yummly_image_url',
        ),
    ]
