# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170407_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='related_recipes',
            field=models.ManyToManyField(related_name='_recipe_related_recipes_+', to='main.Recipe'),
        ),
    ]
