# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_recipe_related_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.NullBooleanField(default=None)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='dateModified',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='isUserRecipe',
            new_name='is_user_uecipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='isYummlyRecipe',
            new_name='is_yummly_recipe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_recipes',
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_recipe',
            field=models.ManyToManyField(related_name='saved_recipes', to='main.Recipe'),
        ),
        migrations.AddField(
            model_name='recipevote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Recipe'),
        ),
        migrations.AddField(
            model_name='recipevote',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='voted_recipe',
            field=models.ManyToManyField(related_name='voted_recipes', through='main.RecipeVote', to='main.Recipe'),
        ),
    ]
