# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170408_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='voted_recipe',
            new_name='voted_recipes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_recipe',
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_recipes',
            field=models.ManyToManyField(related_name='profiles', to='main.Recipe'),
        ),
    ]
