# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170409_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_user_uecipe',
            new_name='is_user_recipe',
        ),
    ]
