# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170409_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='rating',
            new_name='yummly_rating',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='source',
            new_name='yummly_source',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='time_in_seconds',
            new_name='yummly_time_in_seconds',
        ),
    ]
