# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170419_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yummly_image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yummly_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yummly_source',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yummly_time_in_seconds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yummly_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
