# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170421_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='related_recipes',
            field=models.ManyToManyField(blank=True, related_name='_recipe_related_recipes_+', to='main.Recipe'),
        ),
    ]
